Repository dbt-labs/dbt-athena, pull requests merged in 2022-12, with the labels that each got.

#83 release: Release 1.3.3
  dbt/adapters/athena/__version__.py
Labels: release

#85 fix: Add more information to default profile
  dbt/include/athena/profile_template.yml
  dbt/include/athena/sample_profiles.yml
Labels: enhancement

#99 fix: path should be dropped for append
  dbt/include/athena/macros/adapters/relation.sql
Labels: bug

#105 chore: add weekly dependabot
  .github/dependabot.yml
Labels: enhancement
