Repository dbt-labs/dbt-athena, pull requests merged in 2022-11, with the labels that each got.

#9 Get model owner from manifest
  dbt/adapters/athena/impl.py
  dbt/include/athena/macros/adapters/metadata.sql
Labels: enhancement

#7 Release 1.0.4
  CHANGELOG.md
  dbt/adapters/athena/connections.py
  dbt/adapters/athena/impl.py
  dbt/adapters/athena/query_headers.py
  dbt/adapters/athena/relation.py
  dbt/adapters/athena/session.py
  dbt/include/athena/macros/adapters/metadata.sql
  dbt/include/athena/macros/materializations/models/incremental/helpers.sql
  setup.py
Labels: release

#21 Release 1.3.0
  CHANGELOG.md
  README.md
  dbt/adapters/athena/connections.py
  requirements.txt
  setup.py
Labels: release

#27 Trigger publishing to pypi on tag/release
  .github/workflows/python-publish.yml
Labels: enhancement

#24 chore: add linting, pre-commit and github actions
  .flake8
  .github/workflows/ci.yml
  .gitignore
  .pre-commit-config.yaml
  Makefile
  README.md
  dbt/adapters/athena/__init__.py
  dbt/adapters/athena/connections.py
  dbt/adapters/athena/impl.py
  dbt/adapters/athena/query_headers.py
  dbt/adapters/athena/relation.py
  dbt/adapters/athena/session.py
  dbt/include/athena/__init__.py
  dbt/include/athena/macros/adapters/metadata.sql
  dev-requirements.txt
  dev.env
  dev_requirements.txt
  pyproject.toml
  requirements.txt
  setup.py
Labels: chore

#31 Override datediff and dateadd functions to support metrics
  dbt/adapters/athena/__init__.py
  dbt/include/athena/macros/utils/dateadd.sql
  dbt/include/athena/macros/utils/datediff.sql
Labels: bug, feature

#34 Feature/table iceberg
  README.md
  dbt/adapters/athena/impl.py
  dbt/include/athena/macros/materializations/models/helpers_iceberg.sql
  dbt/include/athena/macros/materializations/models/table/table.sql
Labels: feature

#32 Handle error while cleaning partitions
  dbt/adapters/athena/impl.py
Labels: bug

#40 Fix edge case on Iceberg types
  dbt/include/athena/macros/materializations/models/helpers_iceberg.sql
Labels: bug

#26 Create datatypes.sql
  dbt/include/athena/macros/adapters/datatypes.sql
Labels: feature

#39 Support s3_data_dir and s3_data_naming
  README.md
  dbt/adapters/athena/connections.py
  dbt/adapters/athena/impl.py
  dbt/include/athena/macros/materializations/models/helpers_iceberg.sql
  dbt/include/athena/macros/materializations/models/table/create_table_as.sql
  dbt/include/athena/macros/materializations/seeds/helpers.sql
Labels: enhancement, feature

#33 chore: add function tests for utils macros
  .env.example
  .gitignore
  Makefile
  README.md
  dbt/include/athena/macros/utils/any_value.sql
  dbt/include/athena/macros/utils/array_append.sql
  dbt/include/athena/macros/utils/array_concat.sql
  dbt/include/athena/macros/utils/array_construct.sql
  dbt/include/athena/macros/utils/bool_or.sql
  dbt/include/athena/macros/utils/date_trunc.sql
  dbt/include/athena/macros/utils/hash.sql
  dbt/include/athena/macros/utils/right.sql
  dbt/include/athena/macros/utils/safe_cast.sql
  dbt/include/athena/macros/utils/timestamps.sql
  dev-requirements.txt
  dev.env
  pyproject.toml
  test/integration/athena.dbtspec
  tests/__init__.py
  tests/conftest.py
  tests/functional/adapter/fixture_datediff.py
  tests/functional/adapter/utils/test_utils.py
Labels: feature, chore

#30 Support `on_schema_change` feature on incremental model
  README.md
  dbt/adapters/athena/__init__.py
  dbt/adapters/athena/query_headers.py
  dbt/include/athena/macros/adapters/columns.sql
  dbt/include/athena/macros/materializations/models/helpers_iceberg.sql
  dbt/include/athena/macros/materializations/models/incremental/helpers.sql
  dbt/include/athena/macros/materializations/models/incremental/incremental.sql
  dbt/include/athena/macros/materializations/models/incremental/on_schema_change.sql
  dbt/include/athena/macros/utils/ddl_data_type.sql
Labels: feature

#47 feat: add incremental append and merge for iceberg tables
  README.md
  dbt/adapters/athena/connections.py
  dbt/include/athena/macros/materializations/models/helpers_iceberg.sql
  dbt/include/athena/macros/materializations/models/incremental/helpers.sql
  dbt/include/athena/macros/materializations/models/incremental/incremental.sql
  dbt/include/athena/macros/materializations/models/incremental/merge.sql
  dbt/include/athena/macros/materializations/models/table/table.sql
Labels: feature

#53 Prepare release v1.3.2
  CHANGELOG.md
  setup.py
Labels: release

#55 chore: move all utlity macros in utils or helpers
  dbt/include/athena/macros/adapters/columns.sql
  dbt/include/athena/macros/materializations/models/incremental/column_helpers.sql
  dbt/include/athena/macros/utils/datatypes.sql
Labels: chore

#59 Add version in the adapter
  dbt/adapters/athena/__version__.py
  setup.py
Labels: bug, enhancement

#61 Some general tweaks
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
Labels: documentation, enhancement

#56 Fix query comments in case of alter and vacuum
  dbt/adapters/athena/query_headers.py
Labels: bug

#57 fix: incremental table with insert_overwrite
  README.md
  dbt/include/athena/macros/materializations/models/incremental/incremental.sql
Labels: bug

#63 chore: add unit tests
  .github/workflows/ci.yml
  Makefile
  README.md
  dbt/adapters/athena/impl.py
  dbt/adapters/athena/query_headers.py
  dev-requirements.txt
  tests/conftest.py
  tests/unit/__init__.py
  tests/unit/constants.py
  tests/unit/test_adapter.py
  tests/unit/test_config.py
  tests/unit/test_connection_manager.py
  tests/unit/test_formatter.py
  tests/unit/test_query_headers.py
  tests/unit/test_session.py
  tests/unit/utils.py
Labels: chore, relevant
