Repository dbt-labs/dbt-athena, pull requests merged in 2023-02, with the labels that each got.

#111 feat: Implement SCD 6 snapshots
  README.md
  dbt/adapters/athena/impl.py
  dbt/include/athena/macros/materializations/snapshots/snapshot.sql
Labels: feature, relevant

#138 fix: improve clean-up table
  dbt/adapters/athena/impl.py
Labels: bug, chore

#134 chore: upgrade to dbt core v1.4.0
  .github/workflows/ci.yml
  Makefile
  README.md
  dbt/adapters/athena/__version__.py
  dbt/adapters/athena/connections.py
  dbt/adapters/athena/impl.py
  dbt/adapters/athena/relation.py
  dev-requirements.txt
  requirements.txt
  setup.py
  tests/conftest.py
  tests/unit/test_adapter.py
Labels: relevant, dependencies

#141 chore: refactor boto3 calls and expose more functions
  dbt/adapters/athena/impl.py
  dbt/include/athena/macros/materializations/models/table/create_table_as.sql
  tests/unit/constants.py
  tests/unit/test_adapter.py
Labels: enhancement, chore

#143 chore: get boto3 client in function and cover some edge cases
  dbt/adapters/athena/impl.py
  tests/unit/test_adapter.py
  tests/unit/utils.py
Labels: enhancement, chore

#137 fix: Utilize cache for snapshots
  dbt/include/athena/macros/materializations/snapshots/snapshot.sql
Labels: enhancement

#128 feat: add table_hive_ha materialization
  README.md
  dbt/adapters/athena/impl.py
  dbt/include/athena/macros/materializations/models/table/create_table_as.sql
  dbt/include/athena/macros/materializations/models/table/table_hive_ha.sql
  dev-requirements.txt
  tests/unit/test_adapter.py
  tests/unit/utils.py
Labels: enhancement, feature
