Repository dbt-labs/dbt-athena, pull requests merged in 2023-03, with the labels that each got.

#173 fix: add render hive in alter statements
  dbt/include/athena/macros/materializations/models/incremental/column_helpers.sql
Labels: bug

#160 fix: support work groups with default output location configured
  .gitignore
  README.md
  dbt/adapters/athena/impl.py
  dbt/include/athena/macros/materializations/models/table/create_table_as.sql
  tests/unit/constants.py
  tests/unit/test_adapter.py
  tests/unit/utils.py
Labels: enhancement

#159 feat: lake formation tag support
  README.md
  dbt/adapters/athena/connections.py
  dbt/adapters/athena/impl.py
  dbt/include/athena/macros/adapters/schema.sql
  dbt/include/athena/macros/materializations/models/incremental/incremental.sql
  dbt/include/athena/macros/materializations/models/table/table.sql
  dbt/include/athena/macros/materializations/models/view/create_or_replace_view.sql
  dbt/include/athena/macros/materializations/seeds/helpers.sql
  dbt/include/athena/sample_profiles.yml
  tests/unit/constants.py
  tests/unit/test_adapter.py
Labels: feature

#185 feat: lakeformation tags for columns support
  README.md
  dbt/adapters/athena/impl.py
  dbt/include/athena/macros/materializations/models/incremental/incremental.sql
  dbt/include/athena/macros/materializations/models/table/table.sql
  dbt/include/athena/macros/materializations/models/view/create_or_replace_view.sql
  dbt/include/athena/macros/materializations/seeds/helpers.sql
  pyproject.toml
  tests/unit/test_adapter.py
Labels: enhancement

#189 fix: Ignore iceberg columns that are not current
  dbt/adapters/athena/impl.py
  tests/unit/test_adapter.py
Labels: bug, enhancement

#161 feat: support larger seed files
  dbt/adapters/athena/impl.py
  dbt/include/athena/macros/materializations/seeds/helpers.sql
  tests/unit/fixtures.py
  tests/unit/test_adapter.py
Labels: enhancement

#153 feat: Snapshot sql compatible with iceberg tables
  README.md
  dbt/include/athena/macros/materializations/snapshots/snapshot.sql
  dbt/include/athena/macros/utils/timestamps.sql
Labels: feature, iceberg
